openapi: 3.0.0
info:
  title: E-Commerce API
  version: 1.0.0
  description: API documentation for E-Commerce API Project

paths:
  /users:
    get:
      summary: Get all users
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
